.\" Copyright (c) 1994
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	$Id: vi.cmd.roff,v 8.9 1994/05/22 12:22:52 bostic Exp $ (Berkeley) $Date: 1994/05/22 12:22:52 $
.\"
#ifdef REFERENCE
.de SP
.sp
..
.Sh VI DESCRIPTION
.Nm \&Vi
takes up the entire screen to display the edited file,
except for the bottom line of the screen.
The bottom line of the screen is used to enter
.Nm \&ex
commands, and for
.Nm \&vi
error and informational messages.
If no other information is being displayed, the current cursor
row and column, if the file has been modified, and the current
mode of the editor can be displayed.
See the
.Sy ruler ,
.Sy showdirty
and
.Sy showmode
options for more information.
.Pp
Empty lines do not have any special representation on the screen,
but lines on the screen that would logically come after the end of
the file are displayed as a single <tilde>
.Pq Dq Li "\&~"
character.
To differentiate between empty lines and lines consisting of only
whitespace characters, use the
.Sy list
option.
Historically, implementations of
.Nm \&vi
have also displayed some lines as single <asterisk>
.Pq Dq Li "\&@"
characters.
These were lines that were not correctly displayed, i.e. lines on the
screen that did not correspond to lines in the file.
.Nm \&Nvi
does not display lines in this fashion.
.Pp
.Nm \&Vi
is a modeful editor, i.e. it has two modes,
.Dq command
and
.Dq "text input" .
When
.Nm \&vi
first starts, it is in command mode.
There are several commands that change
.Nm \&vi
into text input mode.
The <escape> character is used to resolve the text input into the file,
and exit back into command mode.
In
.Nm \&vi
command mode, the cursor is always positioned on the last column of
characters which take up more than one column on the screen.
In
.Nm \&vi
text insert mode, the cursor is positioned on the first column of
characters which take up more than one column on the screen.
.Pp
Generally, if the cursor line and cursor column are not on the screen,
then the screen is scrolled (if the target cursor is close) or repainted
(if the target cursor is far away) so that the cursor is on the screen.
If the screen is scrolled, it is moved a minimal amount, and the cursor
line will usually appear at the top or bottom of the screen.
In the screen is repainted, the cursor line will appear in the center of
the screen, unless the cursor is sufficiently close to the beginning or
end of the file that this isn't possible.
If the
.Sy leftright
option is set, the screen may be scrolled or repainted in a horizontal
direction as well as in a vertical one.
.Pp
A major difference between the historical
.Nm \&vi
presentation and
.Nm \&nvi
is for the scrolling and screen oriented position commands.
.Sy <control-B> ,
.Sy <control-D> ,
.Sy <control-E> ,
.Sy <control-F> ,
.Sy <control-U> ,
.Sy <control-Y> ,
.Sy \&H ,
.Sy \&L
and
.Sy \&H .
In historical implementations of
.Nm \&vi ,
these commands acted on physical, not logical lines.
For lines that were sufficiently long in relation to the size of the
screen, this mean that single line scroll commands might repaint the
entire screen, any scrolling or screen positioning command might not
change the screen or move the cursor at all, and some lines simply
could not be displayed, even though
.Nm \&vi
would edit the file that contained them.
In
.Nm \&nvi ,
these commands act on logical, i.e. screen lines.
You are unlikely to notice any difference unless you're editing files
with lines significantly longer than a screen width.
.Pp
.Nm \&Vi
keeps track of the currently
.Dq "most attractive"
cursor position.
Each command description (for commands that can change the current
cursor position),
specifies if the cursor is set to a specific location in the line,
or if it is moved to the
.Dq "most attractive cursor position" .
The latter means that the cursor is moved to the cursor position
that is vertically as close as possible to the current cursor
position.
If the current line is shorter than than the cursor position
.Nm \&vi
would select, the cursor is positioned on the last character in the line.
In all cases, if the line is empty, the cursor is positioned on the first
column of the line.
If a command moves the cursor to the most attractive position,
it does not alter the current cursor position, and a subsequent
movement will again attempt to move the cursor to that position.
Therefore, although a movement to a line shorter than the currently
most attractive position will cause the cursor to move to the end of
that line, a subsequent movement to a longer line will cause the
cursor to move back to the most attractive position.
.Pp
In addition, the
.Sy \&$
command makes the end of each line the most attractive cursor position
rather than a specific column.
.Pp
Each
.Nm \&vi
command described below notes where the cursor ends up after it is
executed.
This position is described in terms of characters on the line, i.e.
.Dq "the previous character" ,
or,
.Dq "the last character in the line" .
This is to avoid needing to continually refer to on what part of the
character the cursor rests.
.Pp
The following words have special meaning for
.Nm \&vi
commands.
.sp
.Bl -tag -width "XXXX" -compact
.It Sy "previous context"
The position of the cursor before the command which caused the
last non-relative movement was executed.
Each command below which is considered a non-relative movement
is so noted.
In addition, specifying
.Em any
address to an
.Nm \&ex
command is considered a non-relative movement.
.SP
.It Sy "motion"
A second
.Nm \&vi
command can be used as an optional trailing argument to the
.Nm \&vi
.Sy \&! ,
.Sy \&< ,
.Sy \&> ,
.Sy \&c ,
.Sy \&d
and
.Sy \&y
commands.
This command indicates the of the text that's affected by the command.
The motion command may be either the command character repeated (in
which case it means the current line) or a cursor movement command.
In the latter case, the region affected by the command is from the
starting or stopping cursor position which comes first in the file,
to immediately before the starting or stopping cursor position which
comes later in the file.
Commands that operate on lines instead of beginning and ending cursor
positions operate on all of the lines that are wholly or partially
in the region.
In addition, some other commands become line oriented depending on
where they are used.
The command descriptions below note these special cases.
.Pp
The following may all be used as motion components for
.Nm \&vi
commands:
.sp
.ne 12v
.TS
r r r r.
<control-A>	<control-H>	<control-J>	<control-M>
<control-N>	<control-P>	<space>	$
%	'<character>	(	)
+	,	-	/
0	;	?	B
E	F	G	H
L	M	N	T
W	[[	]]	^
\&_	`<character>	b	e
f	h	j	k
l	n	t	w
{	|	}
.TE
.Pp
The optional count prefix available for some of the
.Nm \&vi
commands that take motion commands, or the count prefix available
for the
.Nm \&vi
commands that are used as motion components,
may be included and is
.Em always
considered part of the motion argument.
For example, the commands
.Dq Li c2w
and
.Dq Li 2cw
are equivalent, and the region affected by the
.Sy \&c
command is two words of text.
In addition, if the optional count prefix is specified for both the
.Nm \&vi
command and its motion component, the effect is multiplicative and
is considered part of the motion argument.
For example, the commands
.Dq Li 4cw
and
.Dq Li 2c2w
are equivalent, and the region affected by the
.Sy \&c
command is four words of text.
.SP
.It Sy "count"
A positive number used as an optional argument to most commands,
either to give a size or a position (for display or movement commands),
or as a repeat count (for commands that modify text).
The count argument is always optional and defaults to 1 unless otherwise
noted in the command description.
.Pp
When a
.Nm \&vi
command synopsis shows both a
.Dq Li [buffer]
and
.Dq Li [count] ,
they may be presented in any order.
.SP
.It Sy "bigword"
A set of non-whitespace characters preceded and followed by whitespace
characters or the beginning or end of the file or line.
.Pp
Groups of empty lines (or lines containing only whitespace characters)
are treated as a single bigword.
.SP
.It Sy "word  "
Generally, in languages where it is applicable,
.Nm \&vi
recognizes two kinds of words.
First, a sequence of letters, digits and underscores, delimited at both
ends by: characters other than letters, digits, or underscores; the
beginning or end of a line; the beginning or end of the file.
Second, a sequence of characters other than letters, digits, underscores,
or whitespace characters, delimited at both ends by: a letter, digit,
underscore, or whitespace character;
the beginning or end of a line; the beginning or end of the file.
.Pp
Groups of empty lines (or lines containing only whitespace characters)
are treated as a single word.
.SP
.It Sy "paragraph"
An area of text that begins with either the beginning of a file,
an empty line, or a section boundary, and continues until either
an empty line, section boundary, or the end of the file.
.Pp
Groups of empty lines (or lines containing only whitespace characters)
are treated as a single paragraph.
.Pp
Additional paragraph boundaries can be defined using the
.Sy paragraph
option.
.SP
.It Sy "section"
An area of text that starts with the beginning of the file or a line
whose first character is an open brace
.Pq Dq Li "\&{"
and continues until the next section or the end of the file.
Additional section boundaries can be defined using the
.Sy sections
option.
.SP
.It Sy "sentence"
An area of text that begins with either the beginning of the file or the
first nonblank character following the previous sentence, paragraph, or
section boundary and continues until the end of the file or a or a period
.Pq Dq Li "\&." ,
exclamation point
.Pq Dq Li "\&!" ,
or question mark
.Pq Dq Li "\&?" ,
character,
followed by either an end-of-line or two whitespace characters.
Any number of closing parentheses
.Pq Dq Li "\&)" ,
brackets
.Pq Dq Li "\&]" ,
or double-quote
.Pq Dq Li \&"
characters can appear between the period, exclamation point,
or question mark and the whitespace characters or end-of-line.
.Pp
Groups of empty lines (or lines containing only whitespace characters)
are treated as a single sentence.
.El
.bp
#endif /* REFERENCE */
.Sh VI COMMANDS
The following section describes the commands available in the command
mode of the
.Nm \&vi
editor.
In each entry below, the tag line is a usage synopsis for the command
character.
#ifdef REFERENCE
In addition, the final line and column the cursor rests upon,
and any options which affect the command are noted.
#endif
.sp
.Bl -tag -width "XXXX" -compact
.It Sy "[count] <control-A>"
Search forward
.Li count
times for the occurrence of the word upon which the cursor is positioned.
#ifdef REFERENCE
.Pp
The
.Sy <control-A>
command is a non-relative movement.
The
.Sy <control-A>
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line where the word is found.
.It "Column:"
Set to the first character of the word.
.It "Options:"
Affected by the
.Sy extended
and
.Sy wrapscan
options.
.El
#endif
.SP
.It Sy "[count] <control-B>"
Page backwards
.Li count
screens.
#ifdef REFERENCE
Two lines of overlap are maintained by displaying the window
starting at line
.Li "(top_line - count * window_size) + 2" ,
where
.Li window_size
is the value of the
.Sy window
option.
(This size is corrected in the case of split screens, however.)
It is an error if the cursor is on the first line in the file.
.Pp
The
.Sy <control-B>
command is a non-relative movement.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line of text displayed on the screen.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] <control-D>"
Scroll forwards
.Li count
lines.
#ifdef REFERENCE
If
.Li count
is not specified, scroll forwards the number of lines specified by the
last <control-D> or <control-U> command.
If this is the first <control-D> or <control-U> command,
scroll forward half the number of lines in the screen.
This is an error if the movement is past the end of the file.
.Pp
The
.Sy <control-D>
command is a non-relative movement.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line plus the number of lines scrolled.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] <control-E>"
Scroll forward
.Li count
lines, leaving the current line and column as is, if possible.
#ifdef REFERENCE
This is an error if the last line in the file is already displayed
on the screen.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged unless the current line scrolls off the screen,
in which case it's set to the first line on the screen.
.It "Column:"
Unchanged unless the current line scrolls off the screen,
in which case it's the most attractive cursor position.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] <control-F>"
Page forward
.Li count
screens.
#ifdef REFERENCE
Two lines of overlap are maintained by displaying the window
starting at line
.Li "top_line + count * window_size - 2" ,
where
.Li window_size
is the value of the
.Sy window
option.
(This size is corrected in the case of split screens, however.)
It is an error if the cursor is on the last line in the file.
.Pp
The
.Sy <control-F>
command is a non-relative movement.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the first line on the screen.
.It "Column:"
Set to the first nonblank character of the current line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-G>"
Display the file information.
#ifdef REFERENCE
The information includes the current pathname, the current line,
the number of total lines in the file, the current line as a percentage
of the total lines in the file, if the file has been modified,
if the file's name has been changed, and if the edit session is read-only.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-H>"
.It Sy "[count] h"
Move the cursor back
.Li count
characters in the current line.
#ifdef REFERENCE
This is an error if the cursor is on the first character
in the line.
.Pp
The
.Sy <control-H>
and
.Sy \&h
commands may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the previous character, or, the first character of the
line if
.Li count
is greater than or equal to the number of characters before the
cursor in the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] <control-J>"
.It Sy "[count] <control-N>"
.It Sy "[count] j"
Move the cursor down
.Li count
lines without changing the current column.
#ifdef REFERENCE
This is an error if the movement is past the end of the file.
.Pp
The
.Sy <control-J> ,
.Sy <control-N>
and
.Sy \&j
commands may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line plus
.Li count .
.It "Column:"
The most attractive cursor position.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-L>"
.It Sy "<control-R>"
Repaint the screen.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] <control-M>"
.It Sy "[count] +"
Move the cursor down
.Li count
lines to the first nonblank character of that line.
#ifdef REFERENCE
This is an error if the movement is past the end of the file.
.Pp
The
.Sy <control-M>
and
.Sy \&+
commands may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line plus
.Li count .
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] <control-P>"
.It Sy "[count] k"
Move the cursor up
.Li count
lines, without changing the current column.
#ifdef REFERENCE
This is an error if the movement is past the beginning of the file.
.Pp
The
.Sy <control-P>
and
.Sy \&k
commands may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line minus count.
.It "Column:"
The most attractive cursor position.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-T>"
Return to the most recent tag context.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the context of the previous tag command.
.It "Column:"
Set to the context of the previous tag command.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-U>"
Scroll backwards
.Li count
lines.
#ifdef REFERENCE
If
.Li count
is not specified, scroll backwards the number of lines specified by the
last <control-D> or <control-U> command.
If this is the first <control-D> or <control-U> command,
scroll backward half the number of lines in the screen.
This is an error if the movement is past the beginning of the file.
.Pp
The
.Sy <control-U>
command is a non-relative movement.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line minus the amount scrolled.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-W>"
Switch to the next lower screen in the window, or, to the first
screen if there are no lower screens in the window.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the previous cursor position in the window.
.It "Column:"
Set to the previous cursor position in the window.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-Y>"
Scroll backwards
.Li count
lines, leaving the current line and column as is, if possible.
#ifdef REFERENCE
This is an error if the first line in the file is already displayed
on the screen.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged unless the current line scrolls off the screen,
in which case it is set to the last line of text displayed
on the screen.
.It "Column:"
Unchanged unless the current line scrolls off the screen,
in which case it's the most attractive cursor position.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-Z>"
Suspend the current editor session.
#ifdef REFERENCE
If the file has been modified since it was last completely written,
and the
.Sy autowrite
option is set, the file is written before the editor session is
suspended.
If this write fails, the editor session is not suspended.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged.
.It "Options:"
Affected by the
.Sy autowrite
option.
.El
#endif
.SP
.It Sy "<escape>"
Execute
.Nm \&ex
commands or cancel partial commands.
#ifdef REFERENCE
If an
.Nm \&ex
command is being entered (e.g.
.Sy \&/ ,
.Sy \&? ,
.Sy \&:
or
.Sy \&! )
the command is executed.
If a partial command has been entered, e.g.
.Dq Li "[0-9]*" ,
or
.Dq Li "[0-9]*[!<>cdy]" ,
the command is cancelled.
Otherwise, it is an error.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
When an
.Nm \&ex
command is being executed, the current line is set as described for
that command.
Otherwise, unchanged.
.It "Column:"
When an
.Nm \&ex
command is being executed, the current column is set as described for
that command.
Otherwise, unchanged.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "<control-]>"
Push a tag reference onto the tag stack.
#ifdef REFERENCE
The tags files (see the
.Sy tags
option for more information) are searched for a tag matching the
text from the current cursor position to the end of the word.
If a matching tag is found, the current file is discarded and the
file containing the tag reference is edited.
.Pp
If the current file has been modified since it was last completely
written, the command will fail.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the matching tag string.
.It "Column:"
Set to the start of the matching tag string.
.It "Options:"
Affected by the
.Sy tags
and
.Sy taglength
options.
.El
#endif
.SP
.It Sy "<control-^>"
Switch to the most recently edited file.
#ifdef REFERENCE
.Pp
If the file has been modified since it was last completely written,
and the
.Sy autowrite
option is set, the file is written out.
If this write fails, the command will fail.
Otherwise, if the current file has been modified since it was last
completely written, the command will fail.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line the cursor was on when the file was last edited.
.It "Column:"
Set to the column the cursor was on when the file was last edited.
.It "Options:"
Affected by the
.Sy autowrite
option.
.El
#endif
.SP
.It Sy "[count] <space>"
.It Sy "[count] l"
Move the cursor forwards
.Li count
characters without changing the current line.
#ifdef REFERENCE
This is an error if the cursor is on the last character in the line.
.Pp
The
.Sy <space>
and
.Sy \&l
commands may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
In addition, these commands may be used as the motion components
of other commands when the cursor is on the last character in the
line, without error.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the current character plus the next
.Li count
characters, or the end of the line if
.Li count
is greater than the number of characters in the line after the
current character.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] ! motion shell-command(s) <newline>"
Replace text with results from shell command.
#ifdef REFERENCE
Pass the lines specified by the
.Li count
and
.Li motion
arguments as standard input to the program named by the
.Sy shell
option, and replace those lines with the output (both
standard error and standard output) of that command.
.Pp
After the motion is entered,
.Nm \&vi
prompts for arguments to the command.
.Pp
Within the arguments of the command,
.Dq Li \&%
and
.Dq Li \&#
are expanded to the current and alternate pathnames, respectively.
The character
.Dq Li \&!
is expanded with the command text of the previous
.Sy \&!
or
.Sy \&:!
commands.
(Therefore, the command
.Sy \&!!
repeats the previous
.Sy \&!
command.)
The special meanings of
.Dq Li \&% ,
.Dq Li \&# ,
and
.Dq Li \&!
can be overridden by escaping them with a backslash.
If no
.Sy \&!
or
.Sy \&:!
command has yet been executed, it is an error to use an unescaped
.Dq Li \&!
character.
The
.Sy \&!
command does
.Em not
do shell expansion on the strings provided as arguments.
If any of the above expansions change the command the user entered,
the command is redisplayed at the bottom of the screen.
.Pp
.Nm \&Vi
then executes the program named by the
.Sy shell
option, with a
.Fl c
flag followed by the arguments (which are bundled into a single argument).
.Pp
The
.Sy \&!
command is permitted in an empty file.
.Pp
If the file has been modified since it was last completely written,
the
.Sy \&!
command will warn you.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
The first line of the replaced text.
.It "Column:"
The first column of the replaced text.
.It "Options:"
Affected by the
.Sy shell
options.
.El
#endif
.SP
.It Sy "[count] #"
Increment the cursor word.
#ifdef REFERENCE
The current word is incremented by
.Li count ,
or, if
.Li count
is not specified, by the amount of the last increment.
If no word has ever been incremented before, it is incremented by 1.
The format and type of the word are retained unless the new value
cannot be represented in the previous format.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] $"
Move the cursor to the end of a line.
#ifdef REFERENCE
If
.Li count
is specified, the cursor moves down
.Li "count - 1"
lines.
.Pp
It is not an error to use the
.Sy \&$
command when the cursor is on the last character of the line or
when the line is empty.
.Pp
The
.Sy \&$
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the cursor is at, or before the first
nonblank character in the line, in which case it is line oriented.
It is not an error to use the
.Sy \&$
command as a motion component when the cursor is on the last character
of the line, although it is an error when the line is empty.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line plus
.Li count
minus 1.
.It "Column:"
Set to the last character in the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "%"
Move to the matching character.
#ifdef REFERENCE
The cursor moves to the parenthesis or curly brace which
.Em matches
the parenthesis or curly brace found at the current cursor position
or which is the closest one to the right of the cursor on the line.
It is an error to execute the
.Sy \&%
command on a line without a parenthesis or curly brace.
Historically, any
.Li count specified to the
.Sy \&%
command was ignored.
.Pp
The
.Sy \&%
command is a non-relative movement.
The
.Sy \&%
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting point of the region is at
or before the first nonblank character on its line, and the ending
point is at or after the last nonblank character on its line, in
which case it is is line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the matching character.
.It "Column:"
Set to the matching character.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "&"
Repeat the previous substitution command on the current line.
#ifdef REFERENCE
.Pp
Historically, any
.Li count
specified to the
.Sy \&&
command was ignored.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged if the cursor was on the last character of the line,
otherwise, set to the first nonblank character of the line.
.It "Options:"
Affected by the
.Sy edcompatible ,
.Sy extended ,
.Sy ignorecase
and
.Sy magic
options.
.El
#endif
.SP
.It Sy "'<character>"
.It Sy "`<character>"
Return to a context marked by the character <character>.
#ifdef REFERENCE
If <character> is the
.Dq Li \&'
or
.Dq Li \&`
character, return to the previous context.
If
.Li <character>
is any other character,
return to the context marked by that character (see the
.Sy \&m
command for more information).
If the command is the
.Sy \&'
command, only the line is restored, and the cursor is placed on
the first nonblank character of that line.
If the command is the
.Sy \&`
command, both the line and column are restored.
.Pp
It is an error if the context no longer exists because of
line deletion.
(Contexts follow lines that are moved, or which are deleted
and then restored.)
.Pp
The
.Sy \&'
and
.Sy \&`
commands are both non-relative movements.
They may be used as a motion component for other
.Nm \&vi
commands.
For the
.Sy \&'
command, any text copied into a buffer is line oriented.
For the
.Sy \&`
command, any text copied into a buffer is character oriented, unless
it both starts and stops at the first character of the line, in which
case it's line oriented.
In addition,
.Sy \&`
commands which move backward and start at the first character in the
line, or move forwards and end at the first character in the line,
are corrected to the last character of the previous lines.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line from the context.
.It "Column:"
Set to the first nonblank character in the line, for the
.Sy \&'
command, and set to the context's column for the
.Sy \&`
command.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] ("
Back up
.Li count
sentences.
#ifdef REFERENCE
.Pp
The
.Sy \&(
command is a non-relative movement.
The
.Sy \&(
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting and stopping points of the
region are the first column of the line, in which case it is
line oriented.
In the latter case, the stopping point of the region is adjusted
to be the end of the line immediately before it, and not the original
cursor position.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the beginning of the sentence.
.It "Column:"
Set to the first nonblank character of the sentence.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] )"
Move forward
.Li count
sentences.
#ifdef REFERENCE
.Pp
The
.Sy \&)
command is a non-relative movement.
The
.Sy \)
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting point of the region is the
first column of the line, in which case it is line oriented.
In the latter case, if the stopping point of the region is also
the first character in the line, it is adjusted to be the end of the
line immediately before it.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the beginning of the sentence.
.It "Column:"
Set to the first nonblank character of the sentence.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] ,"
Reverse find character
.Li count
times.
#ifdef REFERENCE
Reverse the last
.Sy \&F ,
.Sy \&f ,
.Sy \&T
or
.Sy \&t
command, searching the other way in the line,
.Li count
times.
.Pp
The
.Sy \&,
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the searched-for character.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] -"
Move to first nonblank of previous line,
.Li count
times.
#ifdef REFERENCE
.Pp
This is an error if the movement is past the start of the file.
.Pp
The
.Sy \&-
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the current line minus
.Li count .
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] ."
Repeat the last command that modified text.
#ifdef REFERENCE
The repeated command may be a command and motion component combination.
If
.Li count
is specified, it replaces
.Em both
the count specified for the repeated command, and, if applicable, for
the repeated motion component.
If
.Li count
is not specified, the counts originally specified to the command being
repeated are used again.
.Pp
As a special case, if the
.Sy \&.
command is executed immediately after the
.Sy \&u
command, the change log is rolled forward or backward, depending on
the action of the
.Sy \&u
command.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set as described for the repeated command.
.It "Column:"
Set as described for the repeated command.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "/RE<carriage-return>"
.It Sy "/RE/ [offset]<carriage-return>"
.It Sy "?RE<carriage-return>"
.It Sy "?RE? [offset]<carriage-return>"
.It Sy "N"
.It Sy "n"
Search forward or backward for a regular expression.
#ifdef REFERENCE
The commands beginning with a slash
.Pq Dq Li \&/
character are forward searches, the commands beginning with a
question mark
.Pq Dq Li \&?
are backward searches.
.Nm \&Vi
prompts with the leading character on the last line of the screen
for a string.
It then searches forward or backward in the file for the next
occurrence of the string, which is interpreted as a Basic Regular
Expression.
.Pp
The
.Sy \&/
and
.Sy \&?
commands are non-relative movements.
They may be used as the motion components of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the search started and ended on
the first column of a line, in which case it's line oriented.
In addition, forward searches ending at the first column of a line,
and backward searches beginning at the first column of the line,
are corrected to begin or end at the last column of the previous line.
(Note, forward and backward searches can occur for both
.Sy \&/
and
.Sy \&?
commands, if the
.Sy wrapscan
option is set.)
.Pp
If an offset from the matched line is specified (i.e. a trailing
.Dq Li \&/
or
.Dq Li \&?
character is followed by a signed offset), the buffer will always
be line oriented (e.g.
.Dq Li /string/+0
will guarantee a line orientation.
.Pp
The
.Sy \&n
command repeats the previous search.
The
.Sy \&N
command repeats the previous search, but in the reverse direction.
.Pp
Searches may be interrupted using the
.Li <interrupt>
character.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line in which the match occurred.
.It "Column:"
Set to the first character of the matched string.
.It "Options:"
Affected by the
.Sy edcompatible ,
.Sy extended ,
.Sy ignorecase ,
.Sy magic ,
and
.Sy wrapscan
options.
.El
#endif
.SP
.It Sy "0"
Move to the first character in the current line.
#ifdef REFERENCE
It is not an error to use the
.Sy \&0
command when the cursor is on the first character of the line,
however, it is an error to use the
.Sy \&0
command as a motion component in the same situation.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the first character in the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy ":"
Execute an ex command.
#ifdef REFERENCE
.Nm \&Vi
prompts for an
.Nm \&ex
command on the last line of the screen, using a colon
.Pq Dq Li \&:
character, which is then executed.
The command is terminated by a <carriage-return>, <newline> or
<escape> character; all of these characters may be escaped by
using a <literal next> character.
.Pp
If the
.Nm \&ex
command writes to the screen,
.Nm \&vi
will prompt the user for a <carriage-return> before continuing
when the
.Nm \&ex
command finishes.
Large amounts of output from the
.Nm \&ex
command will be paged for the user, and the user prompted for a
<carriage-return> or <space> key to continue, or, in some cases,
a quit (normally a
.Dq Li \&q )
character to interrupt the
.Nm \&ex
command.
.Pp
When the
.Nm \&ex
command finishes, and the user is prompted to resume in visual
mode, it is also possible to enter another
.Dq Li \&:
character followed by another
.Nm \&ex
command.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
The current line is set as described for the
.Nm \&ex
command.
.It "Column:"
The current column is set as described for the
.Nm \&ex
command.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] ;"
Repeat the last character find
.Li count
times.
#ifdef REFERENCE
The last character find is one of the
.Sy \&F ,
.Sy \&f ,
.Sy \&T
or
.Sy \&t
commands.
.Pp
The
.Sy \&;
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
The character searched for.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] < motion"
.It Sy "[count] > motion"
Shift lines left or right.
#ifdef REFERENCE
Shift the number lines in the region specified by the motion component,
times
.Li count ,
left (for the
.Sy <
command) or right (for the
.Sy >
command) by the number of columns specified by the
.Sy shiftwidth
option.
Only whitespace characters are deleted when shifting left;
once the first column of the line contains a nonblank character,
the
.Sy shift
will succeed, but the line will not be modified.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
If the current line is set to one of the lines that are affected
by the command, it is unchanged.
Otherwise, it is set to the first nonblank character of the lowest
numbered line shifted.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
Affected by the
.Sy shiftwidth
option.
.El
#endif
.SP
.It Sy "@ buffer"
Execute a named buffer.
#ifdef REFERENCE
Execute the named buffer as
.Nm \&vi
commands
(including
.Nm \&ex
commands).
If the buffer is line oriented, <newlines> are logically appended
to each line of the buffer.
If the buffer is character oriented, <newlines> are logically
appended to all but the last line in the buffer.
.Pp
If the buffer name is
.Dq Li \&@ ,
or
.Dq Li \&* ,
then the last buffer executed shall be used.
It's an error to specify
.Dq Li \&@@
or
.Dq Li \&**
if there is no last buffer execution.
The text of a macro may contain an
.Sy \&@
command, and it is possible to create infinite loops in this manner.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Dependent on the results of the execution of the command(s).
.It "Column:"
Dependent on the results of the execution of the command(s).
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] A"
Enter input mode, appending the text after the end of the line.
#ifdef REFERENCE
If
.Li count
is specified, the text is repeatedly input
.Li "count - 1"
more times after input mode is exited.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[count] B"
Move backwards
.Li count
bigwords.
#ifdef REFERENCE
Move the cursor backwards to the beginning of a bigword by repeating the
following algorithm: if the current position is at the beginning of a
bigword or the character at the current position cannot be part of a bigword,
move to the first character of the preceding bigword.
Otherwise, move to the first character of the bigword at the current position.
If no preceding bigword exists on the current line, move to the first
character of the last bigword on the first preceding line that contains a
bigword.
.Pp
The
.Sy \&B
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the word selected.
.It "Column:"
Set to the first character of the word selected.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] C"
Change text from the current position to the end-of-line.
#ifdef REFERENCE
If
.Li count
is specified, the input text replaces from the current position to
the end-of-line, plus
.Li "count - 1"
subsequent lines.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[buffer] D"
Delete text from the current position to the end-of-line.
#ifdef REFERENCE
.Pp
It is not an error to execute the
.Sy \&D
command on an empty line.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character before the current character, or, column 1 if
the cursor was on column 1.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] E"
Move forward
.Li count
end-of-bigwords.
#ifdef REFERENCE
Move the cursor forwards to the end of a bigword by repeating the
following algorithm: if the current position is the end of a
bigword or the character at that position cannot be part of a bigword,
move to the last character of the following bigword.
Otherwise, move to the last character of the bigword at the current
position.
If no succeeding bigword exists on the current line,
move to the last character of the first bigword on the next following
line that contains a bigword.
.Pp
The
.Sy \&E
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the word selected.
.It "Column:"
Set to the last character of the word selected.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] F <character>"
Search
.Li count
times backward through the current line for
.Li <character> .
#ifdef REFERENCE
.Pp
The
.Sy \&F
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character searched for.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] G"
Move to line
.Li count ,
or the last line of the file if
.Li count
not specified.
#ifdef REFERENCE
.Pp
The
.Sy \&G
command is a non-relative movement.
The
.Sy \&G
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to
.Li count ,
if specified, otherwise, the last line.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] H"
Move to the line
.Li "count - 1"
lines below the top of the screen.
#ifdef REFERENCE
.Pp
The
.Sy \&H
command is a non-relative movement.
The
.Sy \&H
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line
.Li "count - 1"
lines below the top of the screen.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] I"
Enter input mode, inserting the text at the beginning of the line.
#ifdef REFERENCE
If
.Li count
is specified, the text input is repeatedly input
.Li "count - 1"
more times.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] J"
Join lines.
#ifdef REFERENCE
Join the current line with the next line.
If the current line ends with al whitespace character, all whitespace
is stripped from the next line.
Otherwise, if the next line starts with a open parenthesis
.Pq Dq Li "\&(" ,
do nothing.
Otherwise, if the current line ends with a question mark
.Pq Dq Li "\&?" ,
period
.Pq Dq Li "\&."
or exclamation point
.Pq Dq Li "\&!" ,
insert two spaces.
Otherwise, insert a single space.
If
.Li count
is specified,
.Li count
lines are joined; a minimum of two lines are always joined, regardless
of the value of
.Li count .
.Pp
It is not an error to join lines past the end of the file,
i.e. lines that don't exist.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character after the last character of the next-to-last
joined line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] L"
Move to the line
.Li "count - 1"
lines above the bottom of the screen.
#ifdef REFERENCE
.Pp
The
.Sy \&L
command is a non-relative movement.
The
.Sy \&L
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line
.Li "count - 1"
lines below the top of the screen.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy " M"
Move to the line in the middle of the screen.
#ifdef REFERENCE
.Pp
The
.Sy \&M
command is a non-relative movement.
The
.Sy \&M
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
Historically, any
.Li count
specified to the
.Sy \&M
command was ignored.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line in the middle of the screen.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] O"
Enter input mode, appending text in a new line above the current line.
#ifdef REFERENCE
If
.Li count
is specified, the text input is repeatedly input
.Li "count - 1"
more times.
.Pp
Historically, any
.Li count
specified to the
.Sy \&O
command was ignored.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[buffer] P"
Insert text from a buffer.
#ifdef REFERENCE
Insert text from the specified buffer (the unnamed buffer by default)
before the current column or, if the buffer is line oriented,
the current line.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the lowest numbered line insert,
if the buffer is line oriented, otherwise unchanged.
.It "Column:"
Set to the first nonblank character of the appended text,
if the buffer is line oriented, otherwise, the last character
of the appended text.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "Q"
Exit
.Nm \&vi
(or visual) mode and switch to
.Nm \&ex
mode.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
No longer relevant.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] R"
Enter input mode, replacing the characters in the current line.
#ifdef REFERENCE
If
.Li count
is specified, the text input is repeatedly input
.Li "count - 1"
more times.
.Pp
If the end of the current line is reached, no more characters are
replaced and any further characters input are appended to the line.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[buffer] [count] S"
Substitute
.Li count
lines.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[count] T <character>"
Search backwards,
.Li count
times,
through the current line for the character
.Em after
the specified <character>.
#ifdef REFERENCE
.Pp
The
.Sy \&T
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character
.Em after
the character searched for.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "U"
Restore the current line to its state before the cursor last
moved to it.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
The first character.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] W"
Move forward
.Li count
bigwords.
#ifdef REFERENCE
Move the cursor forwards to the beginning of a bigword by repeating the
following algorithm: if the current position is within a bigword or the
character at that position cannot be part of a bigword, move to the first
character of the next bigword.
If no subsequent bigword exists on the current line,
move to the first character of the first bigword on the first following
line that contains a bigword.
.Pp
The
.Sy \&W
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
The line containing the word selected.
.It "Column:"
The last character of the word selected.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] X"
Delete
.Li count
characters before the cursor.
#ifdef REFERENCE
If the number of characters to be deleted is greater than or equal to
the number of characters to the beginning of the line, all of the
characters before the current cursor position, to the beginning of the
line, are deleted.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the current character minus
.Li count ,
or the first character if count is greater than the number of
characters in the line before the cursor.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] Y"
Copy (or
.Dq yank )
.Li count
lines into the specified buffer.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "ZZ"
Write the file and exit
.Nm \&vi .
#ifdef REFERENCE
The file is only written if it has been modified since the last
complete write of the file to any file.
.Pp
The
.Sy ZZ
command will exit the editor after writing the file,
if there are no further files to edit.
Entering two
.Dq quit
commands (i.e.
.Sy wq ,
.Sy quit ,
.Sy xit
or
.Sy ZZ )
in a row) will override this check and the editor will exit,
unless the write fails.
#endif
.SP
.It Sy "[count] [["
Back up
.Li count
section boundaries.
#ifdef REFERENCE
.Pp
The
.Sy \&[[
command is a non-relative movement.
The
.Sy \&[[
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting position is column 0
in which case it is line oriented.
.Pp
This is an error if the cursor is on the first line of the file.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the previous line that is
.Li count
section boundaries back,
or the first line of the file if no more section boundaries exist
preceding the current line.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
Affected by the
.Sy sections
option.
.El
#endif
.SP
.It Sy "[count] ]]"
Move forward
.Li count
section boundaries.
#ifdef REFERENCE
.Pp
The
.Sy \&]]
command is a non-relative movement.
The
.Sy \&]]
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting position is column 0
in which case it is line oriented.
.Pp
This is an error if the cursor is on the first line of the file.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line that is
.Li count
section boundaries forward,
or to the last line of the file if no more section
boundaries exist following the current line.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
Affected by the
.Sy sections
option.
.El
#endif
.SP
.It Sy "^"
Move to first nonblank character on the current line.
#ifdef REFERENCE
.Pp
The
.Sy \&^
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the first nonblank character of the current line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] _"
Move down
.Li "count - 1"
lines, to the first nonblank character.
#ifdef REFERENCE
.Pp
The
.Sy \&_
command is a non-relative movement.
The
.Sy \&_
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
line oriented.
.Pp
It is not an error to execute the
.Sy \&_
command when the cursor is on the first character in the line.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
The current line plus
.Li "count - 1" .
.It "Column:"
The first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] a"
Enter input mode, appending the text after the cursor.
#ifdef REFERENCE
If
.Li count
is specified, the text input is repeatedly input
.Li "count - 1"
more times.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[count] b"
Move backwards
.Li count
words.
#ifdef REFERENCE
Move the cursor backward to the beginning of a word by repeating the
following algorithm: if the current position is at the beginning of a word,
move to the first character of the preceding word.
Otherwise, the current position moves to the first character of the word
at the current position.
If no preceding word exists on the current line, move to the first
character of the last word on the first preceding line that contains
a word.
.Pp
The
.Sy \&b
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the word selected.
.It "Column:"
Set to the first character of the word selected.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] c motion"
Change a region of text.
#ifdef REFERENCE
If only part of a single line is affected, then the last character
being changed is marked with a
.Dq Li $ .
Otherwise, the region of text is deleted, and input mode is entered.
.Pp
If
.Li count
is specified, it is applied to the
.Li motion .
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[buffer] [count] d motion"
Delete a region of text.
#ifdef REFERENCE
If
.Li count
is specified, it is applied to the
.Li motion .
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line where the region starts.
.It "Column:"
Set to the character after where the region starts.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] e"
Move forward
.Li count
end-of-words.
#ifdef REFERENCE
Move the cursor forward to the end of a word by repeating the following
algorithm: if the current position is the end of a word,
move to the last character of the following word.
Otherwise, move to the last character of the word at the current position.
If no succeeding word exists on the current line, move to the last character
of the first word on the next following line that contains a word.
.Pp
The
.Sy \&e
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the word selected.
.It "Column:"
Set to the last character of the word selected.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] f<character>"
Search forward,
.Li count
times, through the rest of the current line for <character>.
#ifdef REFERENCE
.Pp
The
.Sy \&f
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character searched for.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] i"
Enter input mode, inserting the text before the cursor.
#ifdef REFERENCE
If
.Li count
is specified, the text input is repeatedly input
.Li "count - 1"
more times.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "m <character>"
Save the current context (line and column) as
.Li <character> .
#ifdef REFERENCE
The exact position is referred to by
.Dq Li `<character> .
The line is referred to by
.Dq Li '<character> .
.Pp
Historically,
.Li <character>
was restricted to lower-case letters only.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] o"
Enter input mode, appending text in a new line under the current line.
#ifdef REFERENCE
If
.Li count
is specified, the text input is repeatedly input
.Li "count - 1"
more times.
.Pp
Historically, any
.Li count
specified to the
.Sy \&o
command was ignored.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[buffer] p"
Append text from a buffer.
#ifdef REFERENCE
Append text from the specified buffer (the unnamed buffer by default)
after the current column or, if the buffer is line oriented, after
the current line.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the first line appended, if the buffer is line oriented,
otherwise unchanged.
.It "Column:"
Set to the first nonblank character of the appended text if the buffer
is line oriented, otherwise, the last character of the appended text.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] r <character>
Replace characters.
#ifdef REFERENCE
The next
.Li count
characters in the line are replaced with
.Li <character> .
Replacing characters with <newline> characters results in creating
new, empty lines into the file.
.Pp
If
.Li <character>
is <escape>, the command is cancelled.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged unless the replacement character is a <newline>,
in which case it is set to the current line plus
.Li "count - 1" .
.It "Column:"
Set to the last character replaced,
unless the replacement character is a <newline>,
in which case the cursor is in column 1 of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] s"
Substitute
.Li count
characters in the current line starting with the current character.
#ifdef REFERENCE
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the last line upon which characters were entered.
.It "Column:"
Set to the last character entered.
.It "Options:"
Affected by the
.Sy altwerase ,
.Sy autoindent ,
.Sy beautify ,
.Sy showmatch ,
.Sy ttywerase
and
.Sy wrapmargin
options.
.El
#endif
.SP
.It Sy "[count] t <character>"
Search forward,
.Li count
times, through the current line for the character immediately
.Em before
<character>.
#ifdef REFERENCE
.Pp
The
.Sy \&t
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character
.Em before
the character searched for.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "u"
Undo the last change made to the file.
#ifdef REFERENCE
If repeated, the
.Sy \&u
command alternates between these two states, and is its own inverse.
When used after an insert that inserted text on more than one line,
the lines are saved in the numeric buffers.
.Pp
The
.Sy \&.
command, when used immediately after the
.Sy \&u
command, causes the change log to be rolled forward or backward,
depending on the action of the
.Sy \&u
command.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the position of the first line changed, if the reversal affects
only one line or represents an addition or change; otherwise, the line
preceding the deleted text.
.It "Column:"
Set to the first nonblank character on line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] w"
Move forward
.Li count
words.
#ifdef REFERENCE
Move the cursor forwards to the beginning of a word by repeating the
following algorithm: if the current position is at the
beginning of a word, move to the first character of the next word.
If no subsequent word exists on the current line, move to the first
character of the first word on the first following line that contains
a word.
.Pp
The
.Sy \&w
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the word selected.
.It "Column:"
Set to the first character of the word selected.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] x"
Delete
.Li count
characters.
#ifdef REFERENCE
The deletion is at the current character position.
If the number of characters to be deleted is greater than or equal to
the number of characters to the end of the line, all of the characters
from the current cursor position to the end of the line are deleted.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Unchanged unless the last character in the line is deleted and the cursor
is not already on the first character in the line, in which case it is
set to the previous character.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[buffer] [count] y motion"
Copy (or
.Dq yank )
a text region specified by the
.Li count
and motion into a buffer.
#ifdef REFERENCE
If
.Li count
is specified, it is applied to the
.Li motion .
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged, unless the region covers more than a single line,
in which case it is set to the line where the region starts.
.It "Column:"
Unchanged, unless the region covers more than a single line,
in which case it is set to the character were the region starts.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count1] z [count2] [-|.|+|^|<carriage-return>"
Redraw, optionally repositioning, the screen.
#ifdef REFERENCE
Redraw the screen with a window
.Li count2
lines long, containing line
.Li count1
placed as specified by character:
.Dq Li \&+
or <carriage-return> specifies the top of the screen,
.Dq Li .
specifies the center of the screen, and
.Dq Li \&-
or
.Dq Li \&^
specifies the bottom of the screen.
If
.Li count1
is not specified, it defaults to the current line, and the action
is as described above except for the
.Dq Li \&^
and
.Dq Li \&+
characters.
The
.Dq Li \&^
character displays the screen before the current screen,
and the
.Dq Li \&+
character displays the screen after the current screen,
similarly to the
.Sy <control-B>
and
.Sy <control-L>
commands.
.Pp
If
.Li count2
is not specified, it default to the current window size.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to
.Li count1 ,
if specified, otherwise unchanged.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] {"
Move backward
.Li count
paragraphs.
#ifdef REFERENCE
.Pp
The
.Sy \&{
command is a non-relative movement.
The
.Sy \&{
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting character is the first
character on its line, in which case it's line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the beginning of the previous paragraph.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
Affected by the
.Sy paragraph
option.
.El
#endif
.SP
.It Sy "[count] |"
Move to a specific
.Em column
position on the current line.
#ifdef REFERENCE
.Pp
The
.Sy \&|
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented.
It's an error to use the
.Sy \&|
command as a motion component and for the cursor to not move.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Unchanged.
.It "Column:"
Set to the character on the column position identified by
.Li count ,
if that position exists in the line.
If the column length of the current line is less than
.Li count ,
the cursor is moved to the last character in the line.
.It "Options:"
None.
.El
#endif
.SP
.It Sy "[count] }"
Move forwards
.Li count
paragraphs.
#ifdef REFERENCE
.Pp
The
.Sy \&}
command is a non-relative movement.
The
.Sy \&}
command may be used as the motion component of other
.Nm \&vi
commands, in which case any text copied into a buffer is
character oriented, unless the starting character is at or
before any nonblank characters in its line,
in which case it's line oriented.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line containing the beginning of the next paragraph.
.It "Column:"
Set to the first nonblank character of the line.
.It "Options:"
Affected by the
.Sy paragraph
option.
.El
#endif
.SP
.It Sy "[count] ~"
Reverse the case of the next
.Li count
character(s).
#ifdef REFERENCE
This is the historic semantic for the
.Sy \&~
command; only in effect if the
.Sy tildeop
option is not set.
.Pp
Lowercase alphabetic characters are changed to uppercase,
and uppercase characters are changed to lowercase.
No other characters are affected.
.Pp
Historically, the
.Sy \&~
command did not move past the end of the current line.
As it has no associated motion, by default, it is difficult to change
the case of large blocks of text.
In
.Nm \&nvi ,
if the cursor is on the last character of a line, and there are
more lines in the file, the cursor moves to the next line.
.Pp
It is not an error to specify a count larger than the number of
characters between the cursor and the end of the file.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line of the character after
.Li count
characters, or, end of file.
.It "Column:"
Set to the character after
.Li count
characters, or, end of file.
.It "Options:"
Affected by the
.Sy tildeop
option.
.El
#endif
.SP
.It Sy "[count] ~ motion"
Reverse the case of the characters in a text region specified by the
.Li count
and
.Li motion .
#ifdef REFERENCE
Only in effect if the
.Sy tildeop
option is set.
.Pp
Lowercase alphabetic characters are changed to uppercase,
and uppercase characters are changed to lowercase.
No other characters are affected.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Set to the line of the character after the last character in the region.
.It "Column:"
Set to the character after the last character in the region.
.It "Options:"
Affected by the
.Sy tildeop
option.
.El
#endif
.SP
.It Sy "<interrupt>"
Interrupt the current operation.
#ifdef REFERENCE
Many of the potentially long-running
.Nm \&vi
commands may be interrupted using the terminal interrupt character.
These operations include searches, file reading and writing, filter
operations and map character expansion.
Interrupts are also enabled when running commands outside of
.Nm \&vi .
.Pp
If the <interrupt> character is used to interrupt while entering an
.Nm \&ex
command, the command is aborted, the cursor returns to its previous
position, and
.Nm \&vi
remains in command mode.
.Pp
Generally, if the <interrupt> character is used to interrupt any
operation, any changes made before the interrupt are left in place.
.Pp
.Bl -tag -width "XOptions:" -compact
.It "Line:"
Dependent on the operation being interrupted.
.It "Column:"
Dependent on the operation being interrupted.
.It "Options:"
None.
.El
#endif
.El
#ifdef REFERENCE
.bp
#endif
.Sh VI TEXT INPUT COMMANDS
The following section describes the commands available in the text
input mode of the
.Nm \&vi
editor.
#ifdef REFERENCE
.Pp
Historically,
.Nm \&vi
implementations only permitted the characters inserted on the current
line to be erased.
In addition, only the
.Dq Li <control-D>
erase character and the
.Dq Li 0<control-D>
and
.Dq Li ^<control-D>
erase strings could erase
.Sy autoindent
characters.
This implementation permits erasure to continue past the beginning
of the current line, and back to where text input mode was entered.
In addition,
.Sy autoindent
characters may be erased using the standard erase characters.
For the line and word erase characters, reaching the
.Sy autoindent
characters forms a
.Dq soft
boundary, denoting the end of the current word or line erase.
Repeating the word or line erase key will erase the
.Sy autoindent
characters.
.Pp
Historically,
.Nm \&vi
always used
.Dq Li <control-H>
and
.Dq Li <control-W>
as character and word erase characters, respectively, regardless of
the current terminal settings.
This implementation accepts, in addition to these two characters,
the current terminal characters for these operations.
#endif
.Pp
.Bl -tag -width "XXXX" -compact
.It Sy "<control-D>"
#ifdef MANUAL
Erase the previous autoindent character.
#endif
#ifdef REFERENCE
If the previous character on the line was an
.Sy autoindent
character, erase it.
Otherwise, if the user is entering the first character in the line,
.Li <control-D>
is ignored.
Otherwise, a literal
.Li <control-D>
character is entered.
#endif
.SP
.It Sy "^<control-D>"
#ifdef MANUAL
Erase all of the autoindent characters, and reset the autoindent level.
#endif
#ifdef REFERENCE
If the previous character on the line was an
.Sy autoindent
character, erase all of the
.Sy autoindent
characters on the line.
In addition, the
.Sy autoindent
level is reset to 0.
#endif
.SP
.It Sy "0<control-D>"
#ifdef MANUAL
Erase all of the autoindent characters.
#endif
#ifdef REFERENCE
If the previous character on the line was an
.Sy autoindent
character, erase all of the
.Sy autoindent
characters on the line.
#endif
.SP
.It Sy "<control-T>"
Insert sufficient <tab> and <space> characters to move the cursor
forward to a column immediately after a column which is an even
multiple of the
.Sy shiftwidth
option.
#ifdef REFERENCE
.Pp
Historically,
.Nm \&vi
did not permit the
.Li \&^T
command to be used unless the cursor was at the first column of a new
line or it was preceded only by
.Sy autoindent
characters.
.Nm \&Nvi
permits it to be used at any time during insert mode.
#endif
.SP
.It Sy "<erase>
.It Sy "<control-H>"
Erase the last character.
.SP
.It Sy "<literal next>"
Quote the next character.
#ifdef REFERENCE
The next character will not be mapped (see the
.Sy map
command for more information)
or interpreted specially.
A placeholder character
.Pq Dq \&^
will be displayed immediately, but will be replaced by the next
character.
#endif
.SP
.It Sy "<escape>
Resolve all text input into the file, and return to command mode.
.SP
.It Sy "<line erase>
Erase the current line.
.SP
.It Sy "<control-W>"
.It Sy "<word erase>
Erase the last word.
The definition of word in this case is dependent on the
.Sy altwerase
and
.Sy ttywerase
options.
.SP
.It Sy "<control-X>[0-9A-Fa-f]*"
Insert a character with the hexadecimal value specified into the text.
.SP
.It Sy "<interrupt>"
Interrupt text input mode, returning to command mode.
#ifdef REFERENCE
If the <interrupt> character is used to interrupt inserting text
into the file, it is as if the <escape> character was used; all
text input up to the interruption is resolved into the file.
#endif
.El
